################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usb_device.c \
E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target/usbd_conf.c \
E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_core.c \
E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_ctlreq.c \
E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usbd_desc.c \
E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_ioreq.c 

OBJS += \
./Middlewares/Composite/USB/COMPOSITE/Core/usb_device.o \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_conf.o \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_core.o \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ctlreq.o \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_desc.o \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ioreq.o 

C_DEPS += \
./Middlewares/Composite/USB/COMPOSITE/Core/usb_device.d \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_conf.d \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_core.d \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ctlreq.d \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_desc.d \
./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ioreq.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/Composite/USB/COMPOSITE/Core/usb_device.o: E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usb_device.c Middlewares/Composite/USB/COMPOSITE/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../../Core/Inc -I../../Composite -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_CUSTOM/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Inc -I../../HARDWARE/LCD -I../../KeyScan -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Composite/USB/COMPOSITE/Core/usbd_conf.o: E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target/usbd_conf.c Middlewares/Composite/USB/COMPOSITE/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../../Core/Inc -I../../Composite -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_CUSTOM/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Inc -I../../HARDWARE/LCD -I../../KeyScan -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Composite/USB/COMPOSITE/Core/usbd_core.o: E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_core.c Middlewares/Composite/USB/COMPOSITE/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../../Core/Inc -I../../Composite -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_CUSTOM/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Inc -I../../HARDWARE/LCD -I../../KeyScan -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Composite/USB/COMPOSITE/Core/usbd_ctlreq.o: E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_ctlreq.c Middlewares/Composite/USB/COMPOSITE/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../../Core/Inc -I../../Composite -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_CUSTOM/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Inc -I../../HARDWARE/LCD -I../../KeyScan -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Composite/USB/COMPOSITE/Core/usbd_desc.o: E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App/usbd_desc.c Middlewares/Composite/USB/COMPOSITE/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../../Core/Inc -I../../Composite -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_CUSTOM/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Inc -I../../HARDWARE/LCD -I../../KeyScan -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/Composite/USB/COMPOSITE/Core/usbd_ioreq.o: E:/Develop/Joker60_V3.5/Joker60_V3_5_Code/Composite/Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Src/usbd_ioreq.c Middlewares/Composite/USB/COMPOSITE/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F401xC -c -I../../Core/Inc -I../../Composite -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/COMPOSITE/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/HID_CUSTOM/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/App -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Core/Inc -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Target -I../../Middlewares/Third_Party/AL94_USB_Composite/COMPOSITE/Class/CDC_ACM/Inc -I../../HARDWARE/LCD -I../../KeyScan -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-Composite-2f-USB-2f-COMPOSITE-2f-Core

clean-Middlewares-2f-Composite-2f-USB-2f-COMPOSITE-2f-Core:
	-$(RM) ./Middlewares/Composite/USB/COMPOSITE/Core/usb_device.cyclo ./Middlewares/Composite/USB/COMPOSITE/Core/usb_device.d ./Middlewares/Composite/USB/COMPOSITE/Core/usb_device.o ./Middlewares/Composite/USB/COMPOSITE/Core/usb_device.su ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_conf.cyclo ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_conf.d ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_conf.o ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_conf.su ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_core.cyclo ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_core.d ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_core.o ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_core.su ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ctlreq.cyclo ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ctlreq.d ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ctlreq.o ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ctlreq.su ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_desc.cyclo ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_desc.d ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_desc.o ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_desc.su ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ioreq.cyclo ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ioreq.d ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ioreq.o ./Middlewares/Composite/USB/COMPOSITE/Core/usbd_ioreq.su

.PHONY: clean-Middlewares-2f-Composite-2f-USB-2f-COMPOSITE-2f-Core

